Add option to disable TLS
owncloud/ocis-proxy pull request #72
Opened 2020-07-15 14:27 UTC by IljaN

Can be used to disable TLS when the ocis-proxy is behind an
TLS-Terminating reverse proxy.

env PROXY_TLS=false or cli --tls=false

Closes #71

2020-07-15 14:30 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/server/http/server.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-proxy/pullRequest?prid=5855953&bid=19171057)

2020-07-15 14:32 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/server/http/server.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-proxy/pullRequest?prid=5855953&bid=19171057)

2020-07-16 07:13 UTC, kulmann requested changes
Code looks good 👍  Please add a changelog item :-)

2020-07-20 08:50 UTC, ownclouders commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/server/http/server.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-proxy/pullRequest?prid=5855953&bid=19171057)

2020-07-20 08:52 UTC, IljaN commented
Woops missing git add...

2020-07-20 12:09 UTC, kulmann approved these changes

2020-07-20 13:23 UTC, refs approved these changes

2020-07-20 13:27 UTC, merged